// Famous Brands portfolio + candidate sites for Sandton/Rosebank corridor, Johannesburg

const BRANDS = [
  { id: "steers",    name: "Steers",       category: "Flame-grilled burgers", color: "#ffb617", ink: "#1a1208", glyph: "S", count: 588 },
  { id: "debonairs", name: "Debonairs",    category: "Pizza",                  color: "#e14a3d", ink: "#fff",   glyph: "D", count: 535 },
  { id: "wimpy",     name: "Wimpy",        category: "Diners",                 color: "#e0211a", ink: "#fff",   glyph: "W", count: 478 },
  { id: "mugg",      name: "Mugg & Bean",  category: "Cafés",                  color: "#7a5230", ink: "#fff",   glyph: "M", count: 196 },
  { id: "fishaways", name: "Fishaways",    category: "Seafood",                color: "#1f8fd6", ink: "#fff",   glyph: "F", count: 199 },
  { id: "milky",     name: "Milky Lane",   category: "Desserts",               color: "#d96aa3", ink: "#fff",   glyph: "ML", count: 115 },
  { id: "vovo",      name: "Vovo Telo",    category: "Bakery cafés",           color: "#c47a2c", ink: "#fff",   glyph: "V", count: 18 },
  { id: "lupa",      name: "Lupa Osteria", category: "Casual dining",          color: "#5b8e4b", ink: "#fff",   glyph: "L", count: 16 },
];

// Site candidates plotted on the map. x/y are 0–100 percent on the map svg.
const SITES = [
  {
    id: "S-114",
    code: "JHB-S-114",
    name: "Sandton Drive · Morningside",
    suburb: "Morningside",
    address: "Cnr Sandton Dr & Rivonia Rd",
    x: 38, y: 28,
    score: 92, tier: "A",
    status: "shortlisted",
    rent: 285, gla: 142,
    foot: 18400, vehicle: 24600,
    catchment: { pop: 142000, hhi: 68500, age: 34 },
    competitors: 3, cannibal: 1.2,
    format: "Drive-thru",
    photoStyle: 1,
    notes: "Corner stand, double frontage, signal-controlled intersection. Lease 5+5.",
  },
  {
    id: "S-118",
    code: "JHB-S-118",
    name: "Rivonia Village",
    suburb: "Rivonia",
    address: "Rivonia Rd & Mutual Rd",
    x: 62, y: 41,
    score: 87, tier: "A",
    status: "new",
    rent: 245, gla: 168,
    foot: 12100, vehicle: 19800,
    catchment: { pop: 96000, hhi: 72200, age: 36 },
    competitors: 4, cannibal: 0.8,
    format: "In-line + patio",
    photoStyle: 2,
    notes: "Strip centre, anchor traffic from Pick n Pay. Patio licence available.",
  },
  {
    id: "S-121",
    code: "JHB-S-121",
    name: "Rosebank Link",
    suburb: "Rosebank",
    address: "Oxford Rd & Bolton Rd",
    x: 22, y: 56,
    score: 95, tier: "A+",
    status: "new",
    rent: 340, gla: 124,
    foot: 28900, vehicle: 31200,
    catchment: { pop: 188000, hhi: 81400, age: 31 },
    competitors: 6, cannibal: 2.1,
    format: "Walk-up flagship",
    photoStyle: 3,
    notes: "Gautrain-adjacent. Heavy lunch + late-night. Premium rent reflects A+ catchment.",
  },
  {
    id: "S-126",
    code: "JHB-S-126",
    name: "Bryanston West",
    suburb: "Bryanston",
    address: "Main Rd & William Nicol",
    x: 11, y: 22,
    score: 78, tier: "B",
    status: "watch",
    rent: 195, gla: 156,
    foot: 6200, vehicle: 22400,
    catchment: { pop: 78000, hhi: 95200, age: 39 },
    competitors: 2, cannibal: 0.4,
    format: "Drive-thru",
    photoStyle: 4,
    notes: "Affluent residential. Lower foot but strong vehicle volumes peak-hour.",
  },
  {
    id: "S-129",
    code: "JHB-S-129",
    name: "Sandton Central",
    suburb: "Sandton CBD",
    address: "Maude St & 5th St",
    x: 49, y: 50,
    score: 84, tier: "A",
    status: "new",
    rent: 410, gla: 98,
    foot: 36400, vehicle: 14200,
    catchment: { pop: 124000, hhi: 88000, age: 33 },
    competitors: 9, cannibal: 3.4,
    format: "Walk-up kiosk",
    photoStyle: 5,
    notes: "Office tower mix. Weekday-skewed. High cannibalisation risk — review.",
  },
  {
    id: "S-133",
    code: "JHB-S-133",
    name: "Hyde Park Corner",
    suburb: "Hyde Park",
    address: "Jan Smuts Ave",
    x: 30, y: 71,
    score: 71, tier: "B",
    status: "watch",
    rent: 320, gla: 88,
    foot: 11200, vehicle: 14800,
    catchment: { pop: 64000, hhi: 112000, age: 41 },
    competitors: 5, cannibal: 0.6,
    format: "In-line",
    photoStyle: 6,
    notes: "Premium catchment but rent demands ATV uplift. Brand fit middling for Steers.",
  },
  {
    id: "S-138",
    code: "JHB-S-138",
    name: "Melrose Arch",
    suburb: "Melrose",
    address: "Melrose Blvd",
    x: 70, y: 64,
    score: 81, tier: "A",
    status: "new",
    rent: 365, gla: 110,
    foot: 22400, vehicle: 12600,
    catchment: { pop: 88000, hhi: 96400, age: 30 },
    competitors: 7, cannibal: 1.6,
    format: "Walk-up flagship",
    photoStyle: 7,
    notes: "Lifestyle precinct, strong evening + weekend.",
  },
  {
    id: "S-142",
    code: "JHB-S-142",
    name: "Parkmore Strip",
    suburb: "Parkmore",
    address: "11th Ave & Grayston",
    x: 56, y: 18,
    score: 68, tier: "B",
    status: "watch",
    rent: 175, gla: 134,
    foot: 4200, vehicle: 18200,
    catchment: { pop: 52000, hhi: 64200, age: 35 },
    competitors: 1, cannibal: 0.2,
    format: "Drive-thru",
    photoStyle: 8,
    notes: "Quiet but low rent + no nearby cannibalisation. Possible value play.",
  },
];

const EXISTING_STORES = [
  { x: 44, y: 38, brand: "steers" },
  { x: 67, y: 30, brand: "debonairs" },
  { x: 18, y: 48, brand: "steers" },
  { x: 52, y: 60, brand: "mugg" },
  { x: 75, y: 52, brand: "wimpy" },
  { x: 40, y: 78, brand: "steers" },
];

const COMPETITORS = [
  { x: 33, y: 32, label: "McD" },
  { x: 47, y: 44, label: "KFC" },
  { x: 60, y: 35, label: "BK" },
  { x: 25, y: 60, label: "KFC" },
  { x: 54, y: 54, label: "McD" },
  { x: 68, y: 58, label: "RC" },
  { x: 28, y: 68, label: "BK" },
];

window.BRANDS = BRANDS;
window.SITES = SITES;
window.EXISTING_STORES = EXISTING_STORES;
window.COMPETITORS = COMPETITORS;
